Repository Egahi/flutterwave-dotnet, pull requests merged in 2020-10, with the labels that each got.

#20 Feature/get all banks
  .github/workflows/build-and-test.yml
  .gitignore
  src/flutterwave-dotnet-test/Apis/BanksTest.cs
  src/flutterwave-dotnet/APIs/Implementations/Banks.cs
  src/flutterwave-dotnet/APIs/Interfaces/IBanks.cs
  src/flutterwave-dotnet/Models/Bank.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetBanksResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
  src/flutterwave-dotnet/Utilities/Endpoints.cs
Labels: enhancement

#21 Feature banks
  .github/workflows/build-and-test.yml
  .gitignore
  README.md
  src/flutterwave-dotnet-test/Apis/BanksTests.cs
  src/flutterwave-dotnet-test/Apis/PaymentsTests.cs
  src/flutterwave-dotnet/APIs/Implementations/Banks.cs
  src/flutterwave-dotnet/APIs/Implementations/Transactions.cs
  src/flutterwave-dotnet/APIs/Interfaces/IBanks.cs
  src/flutterwave-dotnet/Apis/Implementations/Payments.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/IFlutterwaveApi.cs
  src/flutterwave-dotnet/Models/Bank.cs
  src/flutterwave-dotnet/Models/Country.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetBanksResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
  src/flutterwave-dotnet/Utilities/Endpoints.cs
  src/flutterwave-dotnet/Utilities/Extensions.cs
Labels: documentation, enhancement

#28 Feature get bank branches
  README.md
  src/flutterwave-dotnet-test/Apis/BanksTests.cs
  src/flutterwave-dotnet-test/Apis/PaymentsTests.cs
  src/flutterwave-dotnet/APIs/Implementations/Banks.cs
  src/flutterwave-dotnet/APIs/Interfaces/IBanks.cs
  src/flutterwave-dotnet/Models/BankBranch.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetBankBranchesResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: documentation, enhancement

#30 Feature subaccounts
  README.md
  src/flutterwave-dotnet-test/Apis/BanksTests.cs
  src/flutterwave-dotnet-test/Apis/MiscellaneousTests.cs
  src/flutterwave-dotnet-test/Apis/PaymentsTests.cs
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet-test/Apis/TransactionsTests.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/Models/SplitType.cs
  src/flutterwave-dotnet/Models/SubAccount.cs
  src/flutterwave-dotnet/ModelsDTO/Requests/CreateSubAccountRequest.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/CreateSubAccountResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
  src/flutterwave-dotnet/Utilities/Endpoints.cs
Labels: documentation, enhancement

#31 DeleteSubAccount implementation, tests #25
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/DeleteSubAccountResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: enhancement

#32 Worked on the fetch all sub accounts Issue
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/Models/GetSubAccounts.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetSubAccountsResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: enhancement

#33 Feature fetch subaccounts
  README.md
  src/flutterwave-dotnet-test/Apis/BanksTests.cs
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet-test/Apis/TransactionsTests.cs
  src/flutterwave-dotnet/APIs/Implementations/Banks.cs
  src/flutterwave-dotnet/APIs/Implementations/Transactions.cs
  src/flutterwave-dotnet/APIs/Interfaces/IBanks.cs
  src/flutterwave-dotnet/APIs/Interfaces/ITransactions.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/IFlutterwaveApi.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/DeleteSubAccountResponse.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetSubAccountsResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: documentation, enhancement

#37 Feature fetch single subaccount
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/GetSubAccountResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: documentation, enhancement

#36 Vrog update sub account
  README.md
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/Models/UpdateSubAccount.cs
  src/flutterwave-dotnet/ModelsDTO/Requests/UpdateSubAccountRequest.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/UpdateSubAccountResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: documentation, enhancement

#38 Feature update subaccount
  README.md
  src/flutterwave-dotnet-test/Apis/SubAccountsTests.cs
  src/flutterwave-dotnet/APIs/Implementations/Transactions.cs
  src/flutterwave-dotnet/APIs/Interfaces/ITransactions.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/FlutterwaveApi.cs
  src/flutterwave-dotnet/ModelsDTO/Requests/UpdateSubAccountRequest.cs
  src/flutterwave-dotnet/ModelsDTO/Responses/UpdateSubAccountResponse.cs
  src/flutterwave-dotnet/Utilities/AppConstants.cs
Labels: documentation, enhancement

#53 Refactor codebase
  src/flutterwave-dotnet/APIs/Implementations/Banks.cs
  src/flutterwave-dotnet/APIs/Implementations/Transactions.cs
  src/flutterwave-dotnet/APIs/Interfaces/IBanks.cs
  src/flutterwave-dotnet/APIs/Interfaces/ITransactions.cs
  src/flutterwave-dotnet/Apis/Implementations/Miscellaneous.cs
  src/flutterwave-dotnet/Apis/Implementations/Payments.cs
  src/flutterwave-dotnet/Apis/Implementations/SubAccounts.cs
  src/flutterwave-dotnet/Apis/Interfaces/IMiscellaneous.cs
  src/flutterwave-dotnet/Apis/Interfaces/IPayments.cs
  src/flutterwave-dotnet/Apis/Interfaces/ISubAccounts.cs
  src/flutterwave-dotnet/Models/Customer.cs
  src/flutterwave-dotnet/Models/Customizations.cs
  src/flutterwave-dotnet/Models/PageInfo.cs
  src/flutterwave-dotnet/Models/SplitPayment.cs
  src/flutterwave-dotnet/Models/SubAccount.cs
  src/flutterwave-dotnet/Models/Transaction.cs
  src/flutterwave-dotnet/Models/TransactionMeta.cs
  src/flutterwave-dotnet/Requests/CreateSubAccountRequest.cs
  src/flutterwave-dotnet/Requests/InitiatePaymentRequest.cs
  src/flutterwave-dotnet/Requests/SplitPaymentRequest.cs
  src/flutterwave-dotnet/Requests/UpdateSubAccountRequest.cs
  src/flutterwave-dotnet/Requests/VerifyBankAccountRequest.cs
  src/flutterwave-dotnet/Responses/CreateSubAccountResponse.cs
  src/flutterwave-dotnet/Responses/DeleteSubAccountResponse.cs
  src/flutterwave-dotnet/Responses/GetBankBranchesResponse.cs
  src/flutterwave-dotnet/Responses/GetBanksResponse.cs
  src/flutterwave-dotnet/Responses/GetSubAccountResponse.cs
  src/flutterwave-dotnet/Responses/GetSubAccountsResponse.cs
  src/flutterwave-dotnet/Responses/GetTransactionsResponse.cs
  src/flutterwave-dotnet/Responses/InitiatePaymentResponse.cs
  src/flutterwave-dotnet/Responses/Response.cs
  src/flutterwave-dotnet/Responses/UpdateSubAccountResponse.cs
  src/flutterwave-dotnet/Responses/VerifyBankAccountResponse.cs
  src/flutterwave-dotnet/Responses/VerifyTransactionResponse.cs
Labels: enhancement

#54 Add Installation instructions to README.md
  README.md
  src/flutterwave-dotnet/flutterwave-dotnet.csproj
Labels: documentation

#55 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
